import os


import specific_procedures

win = (os.name  == 'nt') #True if Windows
TIME_RENOVATE = 7200

# Параметры подключения mssql
mssql_ut = {'server': 'ns-office-sql',
            'database': 'ut',
            'username': 'k.kobanenko',
            'password': 'pass.....'}
mssql_erp = {'server': 'ns-office-sql',
            'database': 'erp',
            'username': 'k.kobanenko',
            'password': 'pass.....'}
mssql_base77 = {'server': 'ns-office-sql',
            'database': 'base77',
            'username': 'k.kobanenko',
            'password': 'pass.....'}
mssql_fd = {'server': 'ns-office-sql',
            'database': 'fd_analytics',
            'username': 'k.kobanenko',
            'password': 'pass.....'}

SQLconn_str = f"DRIVER={{SQL Server}};SERVER={mssql_ut['server']};DATABASE={mssql_ut['database']};Trusted_Connection=yes"
_1Cconn_str = "Srvr='ns-1c-srv01';Ref='ut';"

# Параметры импортируемых таблиц
_1c_fact_tables = {
    'sales': {'base':'ut', 'table': '_Document134_VT2436'},
    #'sales_retail':{},
    #'prices':{'base':'ut', 'table': '_Document226_VT5671'},
    #'sim':{},
    #'sim_purchase':{},
    #'cost':{},
}





# Настройки SSH
ssh_host = '10.21.8.41'
ssh_port = 22
ssh_user = 'kobanenko'
ssh_password = 'sva3sFynAy'

# Настройки для подключения к базе данных
db_host = '10.21.8.41'
"""
db_port = 5432
db_user = 'airflow'
db_password = 'airflow'
db_name = 'operation'
"""
db_port = 5433
db_user = 'postgres_admin'
db_password = 'postgres_admin'
db_name = 'ns_analytics'

legacy_dir_win = "Z:\Выгрузки-1С\legacy"
legacy_dir_docker ='/opt/airflow/data/legacy'
ordinal_dir_win = "Z:\Выгрузки-1С"
ordinal_dir_docker ='/opt/airflow/z'
extract_modification_time_file = '.\data\\extract_modification_time.json' if win else '/opt/airflow/data/extract_modification_time.json'
transform_modification_time_file = '.\data\\transform_modification_time.json' if win else '/opt/airflow/data/transform_modification_time.json'
load_modification_time_file = '.\data\\load_modification_time.json' if win else '/opt/airflow/data/load_modification_time.json'
etl_dir = '.\data' if win else '/opt/airflow/data'

NDS=0.2




docker_legacy_storage ='/opt/airflow/data/legacy'
data_modification_time_file = '.\data\\etl_modification_time.json' if win else '/opt/airflow/data/etl_modification_time.json'

dirs_to_copy = {'sale': os.path.join(legacy_dir_win,'Продажи_csv2') if win else os.path.join(legacy_dir_docker,'Продажи_csv2'),
                'price': os.path.join(legacy_dir_win,'Прайсы_csv') if win else os.path.join(legacy_dir_docker,'Прайсы_csv'),
                }

files_to_copy = {'counterparty': os.path.join(legacy_dir_win,'Контрагенты.csv') if win else os.path.join(legacy_dir_docker,'Контрагенты.csv'),
                'product': os.path.join(legacy_dir_win,'Товары.csv') if win else os.path.join(legacy_dir_docker,'Товары.csv'),
                'offset': os.path.join(legacy_dir_win,'Взаимозачеты.csv') if win else os.path.join(legacy_dir_docker,'Взаимозачеты.csv'),
                'discount': os.path.join(legacy_dir_win,'Скидки.csv') if win else os.path.join(legacy_dir_docker,'Скидки.csv'),
                'pd': os.path.join(legacy_dir_win,'prepayment_discounts.csv') if win else os.path.join(legacy_dir_docker,'prepayment_discounts.csv'),
                 # cube01 and dayly01 are not source files, they are reports
                #'cube01': os.path.join(legacy_dir_win,'Комм куб_Сен2023_на 23.10.2023 (усеч_с 2021г).xlsb') if win else os.path.join(legacy_dir_docker,'Комм куб_Сен2023_на 23.10.2023 (усеч_с 2021г).xlsb'),
                #'dayly01': os.path.join(legacy_dir_win,'Ежедневный отчет_октябрь 2023 new.xlsx') if win else os.path.join(legacy_dir_docker,'Ежедневный отчет_октябрь 2023 new.xlsx'),
                'sales4cube01': os.path.join(legacy_dir_win,'Коммерция_продажи 2023.csv') if win else os.path.join(legacy_dir_docker,'Коммерция_продажи 2023.csv'),
                'sales4cube02': os.path.join(legacy_dir_win,'Коммерция_обр реал_2019-2023_от 16.10.csv') if win else os.path.join(legacy_dir_docker,'Коммерция_обр реал_2019-2023_от 16.10.csv'),
                'ku01': os.path.join(legacy_dir_win,'База КУ_из РФ.xlsx') if win else os.path.join(legacy_dir_docker,'База КУ_из РФ.xlsx'),
                'ku02': os.path.join(legacy_dir_win,'КУ по контрагентам.xlsx') if win else os.path.join(legacy_dir_docker,'КУ по контрагентам.xlsx'),
                'disc_recovery': os.path.join(legacy_dir_win, 'Тандер препаки_Состав_коды.xlsx') if win else os.path.join(
                     legacy_dir_docker, 'Тандер препаки_Состав_коды.xlsx'),
                'cost': os.path.join(legacy_dir_win, 'cost.txt') if win else os.path.join(legacy_dir_docker, 'cost.txt'),
                'sim': os.path.join(legacy_dir_win, 'cost.txt') if win else os.path.join(legacy_dir_docker, 'cost.txt'),
                'sim_purchase': os.path.join(legacy_dir_win,'закупкасим.csv') if win else os.path.join(legacy_dir_docker,'закупкасим.csv'),
                'curr_rates': os.path.join(legacy_dir_win,'curr_rates.csv') if win else os.path.join(legacy_dir_docker,'curr_rates.csv'),
                '3p_calc_wb': os.path.join(legacy_dir_win,'Wildberries_калькулятор 3Р_рабочий.xlsx') if win else os.path.join(legacy_dir_docker,'Wildberries_калькулятор 3Р_рабочий.xlsx'),
                '3p_calc_ozon': os.path.join(legacy_dir_win,'Ozon_калькулятор 3Р_рабочий.xlsx') if win else os.path.join(legacy_dir_docker,'Ozon_калькулятор 3Р_рабочий.xlsx'),
                '3p_calc_ym': os.path.join(legacy_dir_win,'Я.Маркет_калькулятор 3Р_рабочий.xlsx') if win else os.path.join(legacy_dir_docker,'Я.Маркет_калькулятор 3Р_рабочий.xlsx'),
                'sale_daily_2023': os.path.join(legacy_dir_win, 'Коммерция_продажи 2023.csv') if win else os.path.join(
                     legacy_dir_docker, 'Коммерция_продажи 2023.csv'),
                'sale_corr_daily_2023': os.path.join(legacy_dir_win, 'Коммерция_коррект_2023.csv') if win else os.path.join(
                     legacy_dir_docker, 'Коммерция_коррект_2023.csv'),
                 }



columns_rename = {
    'sale' :{'Номенклатура':'sproduct_title',
                     'Контрагент':'scounterparty',
                     'Заказ покупателя':'sorder',
                     'Договор контрагента.Код':'agreem',
                     'Номенклатура.Код':'sproduct_code',
                     'Номенклатура.Артикул':'sarticle',
                     'Тип цен':'sprice_type',
                     'Дата заказа':'sorder_date',
                     'Период, секунда.Начало месяца':'sorder_month',
                     'Заказ покупателя.Предоплата':'sprepayment',
                     'Заказ покупателя.Комментарий':'scommentary',
                     'Контрагент.Код':'scounterparty_code',
                     'Итого':'samount',
                     'Unnamed: 13':'sprice_by_type',
                     'Unnamed: 14':'sprice_includes_nds',
                     'Unnamed: 15':'sprice_real',
                     'Unnamed: 16':'smoney_real',
                     'Unnamed: 17':'ssale_date',
                     'Unnamed: 18':'sdiscount_manual',
                     'Unnamed: 19':'sdiscount_auto'
                     },
    'sale_daily_2023': {'Документ продажи.Тип цен': 'price_type',
             'Контрагент': 'counterparty',
             'Код': 'counterparty_code',
             'Договор контрагента.Номер': 'agreem_code',
             'Номенклатура.Код': 'product_code',
             'Период месяц.Начало месяца': 'month',
             'Количество базовых ед': 'amount',
             'Сумма продаж': 'money',
             'НДС': 'nds'
             },
    'sale_corr_daily_2023': {'Документ продажи.Тип цен': 'price_type',
             'Контрагент': 'counterparty',
             'Код': 'counterparty_code',
             'Договор контрагента.Номер': 'agreem_code',
             'Номенклатура.Код': 'product_code',
             'Период месяц.Начало месяца': 'month',
             'Количество базовых ед': 'amount',
             'Сумма продаж': 'money',
             'НДС': 'nds'
             },
    'price': {'Проведен':'cprocessed',
                       'Дата':'cpriceset_date',
                       'Номер':'cpriceset_id',
                       'Информация':'cpriceset_info',
                       'Ответственный':'cpriceset_responsible',
                       'Комментарий':'cpriceset_commentary',
                       'Номенклатура':'cproduct_title',
                       'Код':'cproduct_code',
                       'Артикул':'carticle',
                       'Тип Цен':'cprice_type',
                       'СНДС без НДС':'cprice_includes_nds',
                       'Цена':'cprice'
                       },
    'offset': {'Статус':'fstatus',
                       'Вид документа':'fdocument_type',
                       'Номер ПП':'fpayorder_number',
                       'Дата ПП':'fpayment_date',
                       'Файлы':'ffiles',
                       'Задачи':'ftasks',
                       'Состояние контроля':'fcontrol_status',
                       'Наименование':'ftitle',
                       'Дата':'fdate',
                       'Организация':'forg_title',
                       'Подразделение':'fdivision',
                       'Контрагенты':'fcounterparties',
                       'Сумма':'fmoney',
                       'Валюта':'fcurrency',
                       'Пометка удаления':'fdelete_mark'
                       },
    'discount': {'клиент Si/SO':'ddiscounts_counterparty',
                          'Код':'dcounterparty_code',
                          'id':'dcode_outdated',
                          'ПР':'ddiscount_pr',
                          'НС':'ddiscount_ns',
                          'PO':'ddiscount_po',
                          'Дата':'ddate',
                          'Канал':'dsale_channel'
                          },
    'pd': {'counterparty_code': 'counterparty_code',
                 'agreem_code': 'agreem_code',
                 'start_date': 'start_date',
                 'discount': 'discount'
                 },
    'counterparty': {'Контрагент':'kcounterparty',
                          'Корр Контрагент':'kcounterparty_korr',
                          'Структура для плана':'kstructure_plan',
                          'Структура Коммерции 1':'kstructure_commerce_1',
                          'Структура Коммерции 2':'kstructure_commerce_2',
                          'Структура Коммерции 3':'kstructure_commerce_3',
                          'Тип цен':'kprice_type',
                          'Тип Цен включает НДС':'kincludes_nds',
                          'Сеть':'knet',
                          'Формат сети':'knet_format',
                          'Код Клиента':'kcounterparty_code',
                          'Организация':'korg_title',
                          'Сеть/Дистрибьютор':'knet_or_distributor',
                          'Регион':'kregion',
                          'Отдел':'kdepartment',
                          'Острочка':'kdeferment',
                          'Округ':'kdisrict',
                          'Страна':'kcountry'
                          },
    'product': {'Код':'pproduct_code',
                        'Наименование':'pproduct_title',
                        'Артикул':'particle',
                        'Тип деятельности':'pactivity_type',
                        'Компания':'pcompany',
                        'Бренд':'pproduct_brand',
                        'Линейка':'pproduct_line',
                        'МБ':'pmb',
                        'Назначение':'pproduct_purpose',
                        'Назначение_детал':'pproduct_purpose_detail',
                        'Назначение_сокр':'pproduct_purpose_short',
                        'Категория':'pproduct_cat',
                        'Категория_сокр':'pproduct_cat_short',
                        'Категория_АМС':'pamc_cat',
                        'Направление':'pproduct_direction',
                        'Эстонский':'pestonian',
                        'Код_безД':'pproduct_code_wod',
                        'Наименование_безД':'pproduct_title_wod',
                        'Артикул_безД':'particle_wod',
                        'Бренд_безД':'pproduct_brand_wod',
                        'Линейка_безД':'pproduct_line_wod',
                        'Назначение_безД':'pproduct_purpose_wod',
                        'Категория_безД':'pproduct_cat_wod',
                        'Артикул_усеч':'pparticle_short',
                        'Код_усеч':'pproduct_short',
                        'Старт продаж':'pstart_date',
                        'Сертификат':'psertificate',
                        'Вложение':'pinclosure'
                        },
    'sales4cube01': {'Документ продажи.Тип цен': 'price_type',
                     'Контрагент': 'counterparty_name',
                     'Код': 'code',
                     'Договор контрагента.Номер': 'agreement_number',
                     'Номенклатура.Код': 'product_code',
                     'Период месяц.Начало месяца': 'month_date',
                     'Количество базовых ед': 'amount',
                     'Сумма продаж': 'sum',
                     'НДС': 'nds'
                     },
    'sales4cube02': {'Документ продажи.Тип цен': 'price_type',
                     'Контрагент': 'counterparty_name',
                     'Код': 'code',
                     'Договор контрагента.Номер': 'agreement_number',
                     'Номенклатура.Код': 'product_code',
                     'Период месяц.Начало месяца': 'month_date',
                     'Количество базовых ед': 'amount',
                     'Сумма продаж': 'sum',
                     'НДС': 'nds'
                     }
}
tables_to_extract = {
    'product': {'file_or_dir': 'file',
                'source': files_to_copy['product'],
                'type': 'csv',
                'delimiter': ';',
                'encoding': None,
                'columns': columns_rename['product'],
                'dropna': ['pproduct_code', 'pproduct_title', 'pstart_date'],
                'drop_duplicates': ['pproduct_code', 'pproduct_title'],
                'types': {'pproduct_code': 'str',
                            'pproduct_title': 'str',
                            'particle': 'str',
                            'pactivity_type': 'str',
                            'pcompany': 'str',
                            'pproduct_brand': 'str',
                            'pproduct_line': 'str',
                            'pmb': 'str',
                            'pproduct_purpose': 'str',
                            'pproduct_purpose_detail': 'str',
                            'pproduct_purpose_short': 'str',
                            'pproduct_cat': 'str',
                            'pproduct_cat_short': 'str',
                            'pamc_cat': 'str',
                            'pproduct_direction': 'str',
                            'pestonian': 'str',
                            'pproduct_code_wod': 'str',
                            'pproduct_title_wod': 'str',
                            'particle_wod': 'str',
                            'pproduct_brand_wod': 'str',
                            'pproduct_line_wod': 'str',
                            'pproduct_purpose_wod': 'str',
                            'pproduct_cat_wod': 'str',
                            'pparticle_short': 'str',
                            'pproduct_short': 'str',
                            'pstart_date': 'datetime64[ns]',
                            'psertificate': 'str',
                            'pinclosure': 'int'
                          },
                'lengths': {'pproduct_code': 50,
                            'pproduct_title': 128,
                            'particle': 32,
                            'pactivity_type': 32,
                            'pcompany': 32,
                            'pproduct_brand': 32,
                            'pproduct_line': 32,
                            'pmb': 32,
                            'pproduct_purpose': 32,
                            'pproduct_purpose_detail': 32,
                            'pproduct_purpose_short': 32,
                            'pproduct_cat': 32,
                            'pproduct_cat_short': 32,
                            'pamc_cat': 32,
                            'pproduct_direction': 32,
                            'pestonian': 8,
                            'pproduct_code_wod': 50,
                            'pproduct_title_wod': 128,
                            'particle_wod': 32,
                            'pproduct_brand_wod': 32,
                            'pproduct_line_wod': 32,
                            'pproduct_purpose_wod': 32,
                            'pproduct_cat_wod': 32,
                            'pparticle_short': 32,
                            'pproduct_short': 32,
                            'psertificate': 32,
                            },
                'decimal_delimiters': {
                },
                'date_formats': {'pstart_date': '%d.%m.%Y'
                                 },
                'spec_proc': specific_procedures.product
                },
    'sale': {'file_or_dir': 'dir',
             'source': dirs_to_copy['sale'],
             'type': 'csv',
             'delimiter': ';',
             'encoding': 'windows-1251',
             'columns': columns_rename['sale'],
             'dropna': ['sproduct_code'],
             'drop_duplicates': ['sorder', 'sproduct_code', 'samount', 'smoney_real', 'scommentary', 'ssale_date'],
             'types': {'sorder': 'str',
                            'sorder_date': 'datetime64[ns]',
                            'sorder_month': 'datetime64[ns]',
                            'sprepayment': 'str',
                            'scommentary': 'str',
                            'scounterparty_code': 'str',
                            'samount': 'int',
                            'sprice_by_type': 'float',
                            'sprice_includes_nds': 'str',
                            'sprice_real': 'float',
                            'smoney_real': 'float',
                            'ssale_date': 'datetime64[ns]',
                            'sdiscount_manual': 'float',
                            'sdiscount_auto': 'float'
                            },
             'lengths': {'sorder': 50,
                        'sprepayment': 50,
                        'scommentary': 512,
                        'scounterparty_code': 50,
                        'sprice_includes_nds': 10,
                        },
             'decimal_delimiters': {'sprice_by_type': [{'from': ',', 'to': '.'},
                                                    {'from': 'Деление на 0', 'to': '0'}],
                                    'sprice_real': [{'from': ',', 'to': '.'},
                                                    {'from': 'Деление на 0', 'to': '0'}],
                                    'smoney_real': [{'from': ',', 'to': '.'},
                                                    {'from': ' ', 'to': ''}],
                                    'sdiscount_manual': [{'from': ',', 'to': '.'}],
                                    'sdiscount_auto': [{'from': ',', 'to': '.'}],
                                    'samount': [{'from': ',', 'to': '.'},
                                                {'from': ' ', 'to': ''}],
                                    },
             'date_formats': {'sorder_date': '%d.%m.%Y',
                                'sorder_month': '%d.%m.%y',
                                'ssale_date': '%d.%m.%Y'
                                }
             },
    'sale_daily_2023': {'file_or_dir': 'file',
                 'source': files_to_copy['sale_daily_2023'],
                 'type': 'csv',
                 'delimiter': ';',
                 'encoding': 'windows-1251',
                 'columns': columns_rename['sale_daily_2023'],
                 'dropna': [],
                 'drop_duplicates': [],
                 'types': {'price_type': 'str',
                           'counterparty': 'str',
                           'counterparty_code': 'str',
                           'agreem_code': 'str',
                           'product_code': 'str',
                           'month': 'datetime64[ns]',
                           'amount': 'int',
                           'money': 'float',
                            'nds': 'float'
                           },
                 'lengths': {'price_type': 32,
                           'counterparty': 32,
                           'counterparty_code': 16,
                           'agreem_code': 16,
                           'product_code': 16,
                             },
                 'decimal_delimiters': {},
                 'date_formats': {'month': '%d.%m.%Y', }
                 },
    'sale_corr_daily_2023': {'file_or_dir': 'file',
                 'source': files_to_copy['sale_corr_daily_2023'],
                 'type': 'csv',
                 'delimiter': ';',
                 'encoding': 'windows-1251',
                 'columns': columns_rename['sale_corr_daily_2023'],
                 'dropna': [],
                 'drop_duplicates': [],
                 'types': {'price_type': 'str',
                           'counterparty': 'str',
                           'counterparty_code': 'str',
                           'agreem_code': 'str',
                           'product_code': 'str',
                           'month': 'datetime64[ns]',
                           'amount': 'int',
                           'money': 'float',
                            'nds': 'float'
                           },
                 'lengths': {'price_type': 32,
                           'counterparty': 32,
                           'counterparty_code': 16,
                           'agreem_code': 16,
                           'product_code': 16,
                             },
                 'decimal_delimiters': {},
                 'date_formats': {'month': '%d.%m.%y', }
                 },
    'price': {'file_or_dir': 'dir',
                'source': dirs_to_copy['price'],
                'type': 'csv',
                'delimiter': ';',
                'encoding': 'windows-1251',
                'columns': columns_rename['price'],
                  'dropna': ['cpriceset_date', 'carticle', 'cprice_type','cprice' ],
                  'drop_duplicates': [],
                  'types': {'cprocessed':'str',
                       'cpriceset_date': 'datetime64[ns]',
                       'cpriceset_id': 'str',
                       'cpriceset_info': 'str',
                       'cpriceset_responsible':'str',
                       'cpriceset_commentary': 'str',
                       'cproduct_title': 'str',
                       'cproduct_code':'str',
                       'carticle':'str',
                       'cprice_type':'str',
                       'cprice_includes_nds': 'str',
                       'cprice': 'float'
                            },
                  'lengths': {'cprocessed':20,
                       'cpriceset_id': 32,
                       'cpriceset_info': 32,
                       'cpriceset_responsible': 64,
                       'cpriceset_commentary': 512,
                       'cproduct_title': 128,
                       'cproduct_code': 32,
                       'carticle': 32,
                       'cprice_type': 64,
                       'cprice_includes_nds': 16
                              },
                  'decimal_delimiters': {'cprice': [{'from': ',', 'to': '.'}],
                                         },
                  'date_formats': {'cpriceset_date': '%d.%m.%y %H:%M:%S'
                                   }
              },
    'counterparty': {'file_or_dir': 'file',
                'source': files_to_copy['counterparty'],
                'type': 'csv',
                'delimiter': ';',
                'encoding': 'windows-1251',
                'columns': columns_rename['counterparty'],
                     'dropna': ['kcounterparty_code'],
                     'drop_duplicates': [],
                     'types': {'kcounterparty': 'str',
                          'kcounterparty_korr': 'str',
                          'kstructure_plan':'str',
                          'kstructure_commerce_1': 'str',
                          'kstructure_commerce_2': 'str',
                          'kstructure_commerce_3': 'str',
                          'kprice_type': 'str',
                          'kincludes_nds': 'str',
                          'knet': 'str',
                          'knet_format': 'str',
                          'kcounterparty_code': 'str',
                          'korg_title': 'str',
                          'knet_or_distributor': 'str',
                          'kregion': 'str',
                          'kdepartment': 'str',
                          'kdeferment': 'str',
                          'kdisrict': 'str',
                          'kcountry': 'str'
                               },
                     'lengths': {'kcounterparty': 64,
                          'kcounterparty_korr': 64,
                          'kstructure_plan': 32,
                          'kstructure_commerce_1': 64,
                          'kstructure_commerce_2': 64,
                          'kstructure_commerce_3': 64,
                          'kprice_type': 32,
                          'kincludes_nds': 16,
                          'knet': 32,
                          'knet_format': 32,
                          'kcounterparty_code': 32,
                          'korg_title': 32,
                          'knet_or_distributor': 32,
                          'kregion': 32,
                          'kdepartment': 16,
                          'kdeferment': 16,
                          'kdisrict': 16,
                          'kcountry': 16
                                 },
                     'decimal_delimiters': {},
                     'date_formats': {}
                },
    'offset': {'file_or_dir': 'file',
                'source': files_to_copy['offset'],
                'type': 'csv',
                'delimiter': ';',
                'encoding': 'windows-1251',
                'columns': columns_rename['offset'],
                'dropna': ['fpayment_date', 'fmoney'],
                'drop_duplicates': [],
                'types': {'fstatus': 'str',
                       'fdocument_type': 'str',
                       'fpayorder_number': 'str',
                       'fpayment_date': 'datetime64[ns]',
                       'ffiles': 'str',
                       'ftasks': 'str',
                       'fcontrol_status': 'str',
                       'ftitle': 'str',
                       'fdate': 'datetime64[ns]',
                       'forg_title': 'str',
                       'fdivision': 'str',
                       'fcounterparties': 'str',
                       'fmoney': 'float',
                       'fcurrency': 'str',
                       'fdelete_mark': 'str'
                         },
                'lengths': {'fstatus': 16,
                       'fdocument_type': 32,
                       'fpayorder_number': 32,
                       'ffiles': 8,
                       'ftasks': 8,
                       'fcontrol_status': 8,
                       'ftitle': 128,
                       'forg_title': 64,
                       'fdivision': 64,
                       'fcounterparties': 128,
                       'fcurrency': 8,
                       'fdelete_mark': 8
                           },
                'decimal_delimiters': {'fmoney': [{'from': ',', 'to': '.'},
                                                  {'from': ' ', 'to': ''}],
                                      },
                'date_formats': {'fpayment_date': '%d.%m.%Y',
                                'fdate': '%d.%m.%Y %H:%M'
                                }
                },
    'discount': {'file_or_dir': 'file',
                'source': files_to_copy['discount'],
                'type': 'csv',
                'delimiter': ';',
                'encoding': 'windows-1251',
                'columns': columns_rename['discount'],
                'dropna': ['ddiscounts_counterparty'],
                'drop_duplicates': [],
                'types': {'ddiscounts_counterparty': 'str',
                      'dcounterparty_code': 'str',
                      'dcode_outdated': 'str',
                      'ddiscount_pr': 'int',
                      'ddiscount_ns': 'int',
                      'ddiscount_po': 'int',
                      'ddate': 'datetime64[ns]',
                      'dsale_channel': 'str'
                       },
                'lengths': {'ddiscounts_counterparty': 64,
                      'dcounterparty_code': 32,
                      'dcode_outdated': 32,
                      'dsale_channel': 32
                         },
                'decimal_delimiters': {},
                'date_formats': {'ddate': '%d.%m.%Y',}
                },
    'sim': {'file_or_dir': 'file',
                'source': files_to_copy['sim'],
                'skiprows': 3,
                'type': 'csv',
                'delimiter': '\t',
                'encoding': 'windows-1251',
                'columns': [f"col{str(k).zfill(2)}" for k in range(10)],
                'dropna': [],
                'drop_duplicates': [],
                'types': {'col00': 'str',
                            'col01': 'str',
                            'col02': 'str',
                            'col03': 'str',
                            'col04': 'str',
                            'col05': 'str',
                            'col06': 'datetime64[ns]',
                            'col07': 'float',
                            'col08': 'str',
                            'col09': 'str',
                },
                'lengths': {},
                'decimal_delimiters': {'col07': [{'from': ',', 'to': '.'},
                                                {'from': ' ', 'to': ''}],},
                'date_formats': {'col06': '%d.%m.%y',},
                'spec_proc': specific_procedures.sim
             },
    'sim_purchase': {'file_or_dir': 'file',
                     'source': files_to_copy['sim_purchase'],
                     'skiprows': 0,
                     'type': 'csv',
                     'delimiter': '\t',
                     'encoding': 'windows-1251',
                     'columns': [f"col{str(k).zfill(2)}" for k in range(30)],
                     'dropna': [],
                     'drop_duplicates': [],
                     'types': {},
                     'lengths': {},
                     'decimal_delimiters': {},
                     'date_formats': {},
                     'spec_proc': specific_procedures.sim_purchase
                     },
    'cost': {'file_or_dir': 'file',
             'source': files_to_copy['cost'],
             'skiprows': 3,
             'type': 'csv',
             'delimiter': '\t',
             'encoding': 'windows-1251',
             'columns': [f"col{str(k).zfill(2)}" for k in range(10)],
             'dropna': [],
             'drop_duplicates': [],
             'types': {'col00': 'str',
                       'col01': 'str',
                       'col02': 'str',
                       'col03': 'str',
                       'col04': 'str',
                       'col05': 'str',
                       'col06': 'datetime64[ns]',
                       'col07': 'float',
                       'col08': 'str',
                       'col09': 'str',
                       },
             'lengths': {},
             'decimal_delimiters': {'col07': [{'from': ',', 'to': '.'},
                                              {'from': ' ', 'to': ''}], },
             'date_formats': {'col06': '%d.%m.%y', },
             'spec_proc': specific_procedures.cost
             },
    'curr_rates': {'file_or_dir': 'internet',
                   'extract_everytime': True,
                   'source': files_to_copy['curr_rates'],
                   'type': 'internet',
                   'columns': [
                       'n',
                       'counterparty_code',
                       'product_name',
                       'article',
                       'product_code',
                       'product_code_nonused',
                       'date_start_sale',
                       'date_end_sale',
                       'erp',
                       'discount',
                       'commentary',
                       'plan_to'
                   ],
                   'dropna': [],
                   'drop_duplicates': [],
                   'types': {'date': 'datetime64[ns]',
                             'rate_USD': 'float',
                             'rate_EUR': 'float',
                             'rate_CNY': 'float', },
                   'lengths': {},
                   'decimal_delimiters': {},
                   'date_formats': {},
                   'extract_spec_proc': specific_procedures.curr_rates
                   },
    'pd': {'file_or_dir': 'file',
                    'source': files_to_copy['pd'],
                    'type': 'csv',
                    'delimiter': ';',
                    'encoding': 'windows-1251',
                    'columns': columns_rename['pd'],
                    'dropna': [],
                    'drop_duplicates': [],
                    'types': {'counterparty_code': 'str',
                             'agreem_code': 'str',
                             'start_date': 'datetime64[ns]',
                             'discount': 'float',
                             },
                    'lengths': {'counterparty_code': 32,
                               'agreem_code': 32,
                               },
                    'decimal_delimiters': {},
                    'date_formats': {'start_date': '%d.%m.%Y', }
                    },
    'sales4cube01': {'file_or_dir': 'file',
                    'source': files_to_copy['sales4cube01'],
                    'sheet_name': 'Коммерция_продажи 2023',
                    'type': 'csv',
                    'encoding': 'windows-1251',
                    'v_slice': slice(1, 1000000),
                    'h_slice': slice(1, 9),
                    'columns': columns_rename['sales4cube01'],
                    'dropna': [],
                    'drop_duplicates': [],
                    'types': {},
                     'lengths': {},
                     'decimal_delimiters': {},
                     'date_formats': {}
                   },
    'sales4cube02': {'file_or_dir': 'file',
                    'source': files_to_copy['sales4cube02'],
                    'sheet_name': 'Коммерция_обр реал_2019-2023_от',
                    'type': 'csv',
                    'encoding': 'windows-1251',
                    'v_slice': slice(1, 1000000),
                    'h_slice': slice(1, 9),
                    'columns': columns_rename['sales4cube02'],
                    'dropna': [],
                    'drop_duplicates': [],
                    'types': {},
                    'lengths': {},
                    'decimal_delimiters': {},
                    'date_formats': {}
                    },
    'ku01': {'file_or_dir': 'file',
                    'source': files_to_copy['ku01'],
                    'sheet_name': 'база_КУ',
                    'type': 'excel',
                    'v_slice': slice(5,1000000),
                    'h_slice': slice(0, 86),
                    'columns': [
                       'counterparty',
                       'old_name',
                       'structure',
                       'country_region',
                       'dictibute_chanel',
                       'counterparty_tradenet_name',
                       'counterparty_tradenet_size',
                       'counterparty_tradenet_format',
                       'counterparty_ceo',
                       'income_lastyear',
                       'price_type',
                       'price_rule',
                       'av_price_indx',
                       'clear_price_indx_compair',
                       'clear_price_indx_full',
                       'tax_sys',
                       'brand_finetune',
                       'date_start',
                       'date_end',
                       'plan_disc_sellin_month',
                       'plan_disc_sellin_quarter',
                       'plan_disc_sellout_month',
                       'plan_disc_sellout_quarter',
                       'mhl_disc',
                       'mktng_budg_by_service_wnds',
                       'mktng_budg_by_service_wonds',
                       'mktng_budg_by_premium_wnds',
                       'mktng_budg_by_premium_wonds',
                       'mktng_disc_in_price_real',
                       'mktng_disc_in_price_nominal',
                       'mktng_disc_pay_frequency',
                       'retro_to_wnds',
                       'retro_to_wonds',
                       'retro_conditional',
                       'retro_conditions',
                       'retro_disc_pay_frequency',
                       'log_to_by_service_wnds',
                       'log_to_by_premium_wnds',
                       'log_to_by_premium_wonds',
                       'log_disc_in_price_real',
                       'log_disc_in_price_nominal',
                       'log_disc_pay_frequency',
                       'other_to_list',
                       'other_to_payment_by_service_wnds',
                       'other_to_payment_by_premium_wnds',
                       'other_to_payment_by_premium_wonds',
                       'other_to_by_discount_real',
                       'other_to_by_discount_nominal',
                       'other_to_pay_frequency',
                       'other_nonto_list',
                       'other_nonto_payment_by_service',
                       'other_nonto_payment_by_premium',
                       'other_nonto_pay_frequency',
                       'other_nonto_comments_if_any',
                       'factoring_bank',
                       'factoring_to_rate_wnds',
                       'factoring_pay_delay_calendar_days',
                       'factoring_pay_delay_working_days',
                       'factoring_pay_delay_start',
                       'factoring_prepayment',
                       'factoring_prepayment_discount',
                       'fine_undelivery_to_rate_wnds',
                       'fine_undelivery_to_rate_wonds',
                       'fine_other_to_list',
                       'fine_other_to_rate_wnds',
                       'fine_other_to_rate_wonds',
                       'fine_undelivery_nonto_sum_wnds',
                       'fine_undelivery_nonto_sum_wonds',
                       'fine_other_nonto_list',
                       'fine_other_nonto_sum_wnds',
                       'fine_other_nonto_sum_wonds',
                       'return_allowed',
                       'return_allowed_pruduct_list',
                       'return_condition',
                       'return_period',
                       'delivery_min_sum',
                       'delivery_who_pays',
                       'delivery_region_list',
                       'delivery_variant',
                       'delivery_cost_to_rate',
                       'delivery_osg_condition',
                       'monthly_to_last_year',
                       'ku_to_rate_wonds',
                       'aggr_ku_to_rate_4_compare',
                       'aggr_ku_nominal_to_rate_4_compare',
                       'aggr_ku_fact_to_rate_4_compare'],
                    'dropna': [],
                    'drop_duplicates': [],
                    'types': {
                           },
                    'lengths': {
                                 },
                     'decimal_delimiters': {},
                     'date_formats': {}
                     },
    'ku02': {'file_or_dir': 'file',
                    'source': files_to_copy['ku02'],
                    'sheet_name': 'КУ',
                    'type': 'excel',
                    'v_slice': slice(1, 999999),
                    'h_slice': slice(0, 29),
                    'columns': [
                       'counterparty_code',
                       'counterparty',
                       'corr_counterparty',
                       'date_month',
                       'NS_reduce_to_perc_wnds',
                       'NS_reduce_to_perc_wonds',
                       'NS_reduce_abs',
                       'PR_reduce_to_perc_wnds',
                       'PR_reduce_to_perc_wonds',
                       'PR_reduce_abs',
                       'RO_reduce_to_perc_wnds',
                       'RO_reduce_to_perc_wonds',
                       'RO_reduce_abs',
                       'log_to_perc_wonds',
                       'log_abs',
                       'extra_to_perc_wonds',
                       'extra_abs',
                       'factoring_to_perc_wonds',
                       'factoring_abs',
                       'channel',
                       'example_expence',
                       'OPEX',
                       'operational_expence',
                       'overlimit_delivery',
                       'over_ku',
                       'consulting',
                       'corners',
                       'other_extras',
                       'comm_ku'
                    ],
                    'dropna': [],
                    'drop_duplicates': [],
                    'types': {
                           },
                    'lengths': {
                             },
                    'decimal_delimiters': {},
                    'date_formats': {}
                    },
    'disc_recovery': {'file_or_dir': 'file',
                    'source': files_to_copy['disc_recovery'],
                    'sheet_name': 'Лист1',
                    'type': 'excel',
                    'v_slice': slice(1, 999999),
                    'h_slice': slice(0, 12),
                    'columns': [
                       'n',
                       'counterparty_code',
                       'product_name',
                       'article',
                       'product_code',
                       'product_code_nonused',
                       'date_start_sale',
                       'date_end_sale',
                       'erp',
                       'discount',
                       'commentary',
                       'plan_to'
                       ],
                    'dropna': [],
                    'drop_duplicates': [],
                    'types': {
                            },
                    'lengths': {
                              },
                    'decimal_delimiters': {},
                    'date_formats': {}
                                       },


}